// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXcP0Iu_zs_jl4zuBLl2iwo2mrVg0AJA8',
    appId: '1:679409694145:web:703a79d62c45e001d8eb40',
    messagingSenderId: '679409694145',
    projectId: 'mobile-lab-45995',
    authDomain: 'mobile-lab-45995.firebaseapp.com',
    storageBucket: 'mobile-lab-45995.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ3QEOVLEMgl_7xvJOC-eYTAPfKXIhfHc',
    appId: '1:679409694145:android:0dbd4d364ae903e6d8eb40',
    messagingSenderId: '679409694145',
    projectId: 'mobile-lab-45995',
    storageBucket: 'mobile-lab-45995.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV9I3j1xqGZ8gH0siMLCxH8dDbr1HrkK0',
    appId: '1:679409694145:ios:c367265639a26b18d8eb40',
    messagingSenderId: '679409694145',
    projectId: 'mobile-lab-45995',
    storageBucket: 'mobile-lab-45995.appspot.com',
    iosClientId: '679409694145-shl3v5urn3muf6pen2ema5qc98mtrhn8.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileLab0120521802',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV9I3j1xqGZ8gH0siMLCxH8dDbr1HrkK0',
    appId: '1:679409694145:ios:c367265639a26b18d8eb40',
    messagingSenderId: '679409694145',
    projectId: 'mobile-lab-45995',
    storageBucket: 'mobile-lab-45995.appspot.com',
    iosClientId: '679409694145-shl3v5urn3muf6pen2ema5qc98mtrhn8.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileLab0120521802',
  );
}
